# Introdcution to scikit-learn (sklearn)
What we're going to learn:
0. End-to-end scikit-learn workflow
1. Getting the data ready
2. Choose the right estimator/algo for our problems
3. Fit the model/algo and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together

## 0. End-to-end scikit-learn workflow

In [19]:
# Get the data ready
import pandas as pd
import numpy as np

heart_disease = pd.read_csv('../matplotlib/heart-disease.csv')
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [20]:
# Create X (features matrix)
X = heart_disease.drop('target', axis=1)
# Create y (target)
y = heart_disease['target']

In [21]:
import warnings
# 'warnings' is used to set a warning filter
warnings.filterwarnings('default')

# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [22]:
# 3, Fit the model and make predictions
from sklearn.model_selection import train_test_split

# Take a 20% of our data for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Use the training data to fit the model
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

0.7868852459016393

In [23]:
# Make a prediction
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0])

In [24]:
# 4. Evaluate the model on the training data and test data (accuracy)
clf.score(X_train, y_train), clf.score(X_test, y_test)

(1.0, 0.7868852459016393)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# This will print a classification report which is a summary of our model performance on the test data set (accuracy, precision, recall, f1 score)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.75      0.76        28
           1       0.79      0.82      0.81        33

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61

In [26]:
# COnfusion matrix is a table that shows the number of true positives, true negatives, false positives and false negatives
confusion_matrix(y_test, y_pred)

array([[21,  7],
       [ 6, 27]])

In [27]:
# Accuracy score is the ratio of the number of correct predictions to the total number of predictions
accuracy_score(y_test, y_pred)

0.7868852459016393

In [28]:
# 5. Improve a model
# Try different amount of estimators

np.random.seed(42)
for i in range(10, 100, 10):
    print(f'Trying model with {i} estimators...')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f'Train accuracy is: {clf.score(X_train, y_train)}')
    print(f'Test accuracy is: {clf.score(X_test, y_test)}')
    print('')

Trying model with 10 estimators...
Train accuracy is: 0.987603305785124
Test accuracy is: 0.7704918032786885

Trying model with 20 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.819672131147541

Trying model with 30 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7704918032786885

Trying model with 40 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7704918032786885

Trying model with 50 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7704918032786885

Trying model with 60 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7540983606557377

Trying model with 70 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.819672131147541

Trying model with 80 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7868852459016393

Trying model with 90 estimators...
Train accuracy is: 1.0
Test accuracy is: 0.7868852459016393

In [29]:
# 6. Save a model and load it 
import pickle

# Pickle is a way to serialize objects in Python, which means converting them into a byte stream that can be saved to a file or sent over a network.
# Here 'wb' means write binary
pickle.dump(clf, open('random_forest_model_1.pkl', 'wb'))

/var/folders/dr/__b71gqn2llgfg4pm0b70kmr0000gn/T/ipykernel_95217/685962717.py:6: ResourceWarning: unclosed file <_io.BufferedWriter name='random_forest_model_1.pkl'>
  pickle.dump(clf, open('random_forest_model_1.pkl', 'wb'))
ResourceWarning: Enable tracemalloc to get the object allocation traceback

In [30]:
# Here 'rb' means read binary
loaded_model = pickle.load(open('random_forest_model_1.pkl', 'rb'))
loaded_model.score(X_test, y_test)

AttributeError: 'RandomForestClassifier' object has no attribute 'get_params_'

---

In [ ]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1. Getting our data ready to be used with machine learning
Three main things we have to do:
1. Split the data into features and labels (usually 'X' and 'y')
2. Filling (also called imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called feature encoding)

In [ ]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X = heart_disease.drop('target', axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [ ]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [31]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [32]:
X.shape

(303, 13)